schema_version: 1

context:
  name: quantem
  version: "0.1.7"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/quantem-${{ version }}.tar.gz
  sha256: 8c8840cd267fd047687f31f46a383bee3d1999c73bddb561702ce2a80f3d69b4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - colorspacious
    - dill
    - numpy >2
    - matplotlib-base
    - scipy
    - tqdm
    - zarr >3
    - cmasher >=1.9.2
    - rosettasciio-base >=0.8.0
    - h5py >=3.13.0

tests:
  - python:
      imports:
        - quantem
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: quantitative electron microscopy analysis toolkit
  homepage: https://github.com/ophusgroup/quantem
  repository: https://github.com/ophusgroup/quantem
  documentation: https://github.com/ophusgroup/quantem

extra:
  recipe-maintainers:
    - gvarnavi
    - cophus
    - matthewfeickert
